// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type BlogDocumentDataSlicesSlice = never;

/**
 * Content for Blog documents
 */
interface BlogDocumentData {
  /**
   * Title field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Blog
   * - **API ID Path**: blog.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogDocumentDataSlicesSlice> /**
   * Meta Title field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Blog document from Prismic
 *
 * - **API ID**: `blog`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<BlogDocumentData>, "blog", Lang>;

type BlogPostDocumentDataSlicesSlice = never;

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
  /**
   * Page Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.page_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  page_title: prismic.KeyTextField;

  /**
   * Excerpt field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  excerpt: prismic.KeyTextField;

  /**
   * Thumbnail field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.thumbnail
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  thumbnail: prismic.ImageField<never>;

  /**
   * Featured Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Content field in *Blog Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Banner field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.banner
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  banner: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Blog Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogPostDocumentDataSlicesSlice> /**
   * Meta Title field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blog Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostDocumentData>,
    "blog_post",
    Lang
  >;

type ExperienceDocumentDataSlicesSlice = never;

/**
 * Content for Experience documents
 */
interface ExperienceDocumentData {
  /**
   * Title field in *Experience*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Experience
   * - **API ID Path**: experience.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Experience*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ExperienceDocumentDataSlicesSlice> /**
   * Meta Title field in *Experience*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: experience.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Experience*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: experience.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Experience*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: experience.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Experience document from Prismic
 *
 * - **API ID**: `experience`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ExperienceDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ExperienceDocumentData>,
    "experience",
    Lang
  >;

/**
 * Item in *Experience Detail → Skill Tags*
 */
export interface ExperienceDetailDocumentDataSkillTagsItem {
  /**
   * Tag field in *Experience Detail → Skill Tags*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: experience_detail.skill_tags[].tag
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  tag: prismic.SelectField<
    | "Javascript"
    | "Typescript"
    | "Next.js"
    | "Vue.js"
    | "React.js"
    | "HTML"
    | "CSS"
    | "Sass"
    | "Tailwind.css"
    | "Adobe XD"
    | "Adobe Target"
    | "Google Analytics"
    | "Google Cloud PLatform"
    | "Google Tag Manager"
    | "Firebase"
    | "WordPress"
    | "Prismic"
    | "Contentful"
    | "Agile"
    | "Scrum"
    | "Unity"
    | "C#"
    | "C++"
    | "Flutter"
    | "Dart"
    | "Optimizely"
    | "A/B Testing"
    | "Feature flags"
  >;
}

type ExperienceDetailDocumentDataSlicesSlice = never;

/**
 * Content for Experience Detail documents
 */
interface ExperienceDetailDocumentData {
  /**
   * Experience Title field in *Experience Detail*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experience_detail.experience_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  experience_title: prismic.KeyTextField;

  /**
   * Company Logo field in *Experience Detail*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: experience_detail.company_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  company_logo: prismic.ImageField<never>;

  /**
   * Company Name field in *Experience Detail*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experience_detail.company_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company_name: prismic.KeyTextField;

  /**
   * Job Title field in *Experience Detail*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experience_detail.job_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  job_title: prismic.RichTextField;

  /**
   * Project Website field in *Experience Detail*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: experience_detail.project_website
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project_website: prismic.LinkField;

  /**
   * Banner field in *Experience Detail*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: experience_detail.banner
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  banner: prismic.ImageField<never>;

  /**
   * Experience Description field in *Experience Detail*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experience_detail.experience_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  experience_description: prismic.RichTextField;

  /**
   * Experience Summary field in *Experience Detail*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experience_detail.experience_summary
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  experience_summary: prismic.RichTextField;

  /**
   * Start Date field in *Experience Detail*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: experience_detail.start_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  start_date: prismic.DateField;

  /**
   * End Date field in *Experience Detail*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: experience_detail.end_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  end_date: prismic.DateField;

  /**
   * Skill Tags field in *Experience Detail*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: experience_detail.skill_tags[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  skill_tags: prismic.GroupField<
    Simplify<ExperienceDetailDocumentDataSkillTagsItem>
  >;

  /**
   * Parent field in *Experience Detail*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: experience_detail.parent
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  parent: prismic.LinkField;

  /**
   * Slice Zone field in *Experience Detail*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: experience_detail.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ExperienceDetailDocumentDataSlicesSlice> /**
   * Meta Title field in *Experience Detail*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: experience_detail.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Experience Detail*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: experience_detail.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Experience Detail*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: experience_detail.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Experience Detail document from Prismic
 *
 * - **API ID**: `experience_detail`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ExperienceDetailDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ExperienceDetailDocumentData>,
    "experience_detail",
    Lang
  >;

type FooterDocumentDataSlicesSlice = never;

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Copyright Rich Text field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.copyright_richtext
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  copyright_richtext: prismic.RichTextField;

  /**
   * `slices` field in *Footer*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<FooterDocumentDataSlicesSlice>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HeaderDocumentDataSlicesSlice = LogoSlice;

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * Title field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Header*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: header.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HeaderDocumentDataSlicesSlice>;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HeaderDocumentData>, "header", Lang>;

type HomeDocumentDataSlicesSlice =
  | RecentPostSliderSlice
  | CompaniesIHaveWorkedWithSliceSlice
  | WelcomeTextSliceSlice
  | MyStackSlice
  | PfpSliceSlice
  | SocialSliceSlice
  | AvailablitySliceSlice
  | AboutMeSliceSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type NavigationDocumentDataSlicesSlice = NavigationItemSlice;

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Name field in *Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Slice Zone field in *Navigation*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NavigationDocumentDataSlicesSlice>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

type PageDocumentDataSlicesSlice = RichTextBlockSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Parent field in *Page*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: page.parent
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  parent: prismic.LinkField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type ServiceDocumentDataSlicesSlice = never;

/**
 * Content for Service_detail documents
 */
interface ServiceDocumentData {
  /**
   * Service Title field in *Service_detail*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.service_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  service_title: prismic.RichTextField;

  /**
   * Service_summary field in *Service_detail*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.service_summary
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  service_summary: prismic.RichTextField;

  /**
   * Banner field in *Service_detail*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service.banner
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  banner: prismic.ImageField<never>;

  /**
   * Service Content field in *Service_detail*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.service_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  service_content: prismic.RichTextField;

  /**
   * Slice Zone field in *Service_detail*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: service.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ServiceDocumentDataSlicesSlice> /**
   * Meta Title field in *Service_detail*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: service.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Service_detail*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: service.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Service_detail*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Service_detail document from Prismic
 *
 * - **API ID**: `service`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServiceDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ServiceDocumentData>,
    "service",
    Lang
  >;

type ServicesDocumentDataSlicesSlice = ServiceSlice;

/**
 * Content for Services documents
 */
interface ServicesDocumentData {
  /**
   * Title field in *Services*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *Services*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: services.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ServicesDocumentDataSlicesSlice> /**
   * Meta Title field in *Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: services.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: services.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Services*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Services document from Prismic
 *
 * - **API ID**: `services`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServicesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ServicesDocumentData>,
    "services",
    Lang
  >;

/**
 * Item in *Settings → Social Links*
 */
export interface SettingsDocumentDataSocialLinksItem {
  /**
   * Social Icon field in *Settings → Social Links*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_links[].social_icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  social_icon: prismic.ImageField<never>;

  /**
   * Social Network field in *Settings → Social Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_links[].social_network
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  social_network: prismic.LinkField;
}

/**
 * Item in *Settings → Footer Links*
 */
export interface SettingsDocumentDataFooterLinksItem {
  /**
   * Link field in *Settings → Footer Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Site Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_description: prismic.KeyTextField;

  /**
   * Social Links field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_links: prismic.GroupField<
    Simplify<SettingsDocumentDataSocialLinksItem>
  >;

  /**
   * Footer Text field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  footer_text: prismic.RichTextField;

  /**
   * Footer Links field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footer_links: prismic.GroupField<
    Simplify<SettingsDocumentDataFooterLinksItem>
  >;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | BlogDocument
  | BlogPostDocument
  | ExperienceDocument
  | ExperienceDetailDocument
  | FooterDocument
  | HeaderDocument
  | HomeDocument
  | NavigationDocument
  | PageDocument
  | ServiceDocument
  | ServicesDocument
  | SettingsDocument;

/**
 * Primary content in *AboutMeSlice → Default → Primary*
 */
export interface AboutMeSliceSliceDefaultPrimary {
  /**
   * About Me Text field in *AboutMeSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_me_slice.default.primary.about_me_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  about_me_text: prismic.RichTextField;

  /**
   * Get in touch CTA field in *AboutMeSlice → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about_me_slice.default.primary.get_in_touch_cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  get_in_touch_cta: prismic.LinkField;

  /**
   * Profile Image field in *AboutMeSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_me_slice.default.primary.profile_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  profile_image: prismic.ImageField<never>;
}

/**
 * Default variation for AboutMeSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutMeSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutMeSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutMeSlice*
 */
type AboutMeSliceSliceVariation = AboutMeSliceSliceDefault;

/**
 * AboutMeSlice Shared Slice
 *
 * - **API ID**: `about_me_slice`
 * - **Description**: AboutMeSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutMeSliceSlice = prismic.SharedSlice<
  "about_me_slice",
  AboutMeSliceSliceVariation
>;

/**
 * Primary content in *AvailablitySlice → Default → Primary*
 */
export interface AvailablitySliceSliceDefaultPrimary {
  /**
   * availability text field in *AvailablitySlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: availablity_slice.default.primary.availability_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  availability_text: prismic.RichTextField;

  /**
   * get in touch field in *AvailablitySlice → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: availablity_slice.default.primary.get_in_touch
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  get_in_touch: prismic.LinkField;
}

/**
 * Default variation for AvailablitySlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AvailablitySliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AvailablitySliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AvailablitySlice*
 */
type AvailablitySliceSliceVariation = AvailablitySliceSliceDefault;

/**
 * AvailablitySlice Shared Slice
 *
 * - **API ID**: `availablity_slice`
 * - **Description**: AvailablitySlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AvailablitySliceSlice = prismic.SharedSlice<
  "availablity_slice",
  AvailablitySliceSliceVariation
>;

/**
 * Item in *CompaniesIHaveWorkedWithSlice → Default → Primary → logo*
 */
export interface CompaniesIHaveWorkedWithSliceSliceDefaultPrimaryLogoItem {
  /**
   * Company Logo field in *CompaniesIHaveWorkedWithSlice → Default → Primary → logo*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: companies_i_have_worked_with_slice.default.primary.logo[].company_logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  company_logo: prismic.ImageField<never>;

  /**
   * Company Name field in *CompaniesIHaveWorkedWithSlice → Default → Primary → logo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: companies_i_have_worked_with_slice.default.primary.logo[].company_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  company_name: prismic.KeyTextField;
}

/**
 * Primary content in *CompaniesIHaveWorkedWithSlice → Default → Primary*
 */
export interface CompaniesIHaveWorkedWithSliceSliceDefaultPrimary {
  /**
   * Title field in *CompaniesIHaveWorkedWithSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: companies_i_have_worked_with_slice.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * logo field in *CompaniesIHaveWorkedWithSlice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: companies_i_have_worked_with_slice.default.primary.logo[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  logo: prismic.GroupField<
    Simplify<CompaniesIHaveWorkedWithSliceSliceDefaultPrimaryLogoItem>
  >;
}

/**
 * Default variation for CompaniesIHaveWorkedWithSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CompaniesIHaveWorkedWithSliceSliceDefault =
  prismic.SharedSliceVariation<
    "default",
    Simplify<CompaniesIHaveWorkedWithSliceSliceDefaultPrimary>,
    never
  >;

/**
 * Slice variation for *CompaniesIHaveWorkedWithSlice*
 */
type CompaniesIHaveWorkedWithSliceSliceVariation =
  CompaniesIHaveWorkedWithSliceSliceDefault;

/**
 * CompaniesIHaveWorkedWithSlice Shared Slice
 *
 * - **API ID**: `companies_i_have_worked_with_slice`
 * - **Description**: CompaniesIHaveWorkedWithSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CompaniesIHaveWorkedWithSliceSlice = prismic.SharedSlice<
  "companies_i_have_worked_with_slice",
  CompaniesIHaveWorkedWithSliceSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * PFP field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.pfp
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  pfp: prismic.ImageField<never>;

  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Subheading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subheading: prismic.RichTextField;

  /**
   * CTA field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.LinkField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Logo → Default → Primary*
 */
export interface LogoSliceDefaultPrimary {
  /**
   * Logo field in *Logo → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logo.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Default variation for Logo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LogoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Logo*
 */
type LogoSliceVariation = LogoSliceDefault;

/**
 * Logo Shared Slice
 *
 * - **API ID**: `logo`
 * - **Description**: Logo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogoSlice = prismic.SharedSlice<"logo", LogoSliceVariation>;

/**
 * Item in *MyStack → Default → Primary → Stack Items*
 */
export interface MyStackSliceDefaultPrimaryStackItemsItem {
  /**
   * Stack Icon field in *MyStack → Default → Primary → Stack Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: my_stack.default.primary.stack_items[].stack_icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  stack_icon: prismic.ImageField<never>;

  /**
   * Stack Skill Number field in *MyStack → Default → Primary → Stack Items*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: my_stack.default.primary.stack_items[].stack_skill_number
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  stack_skill_number: prismic.NumberField;

  /**
   * Stack Title Text field in *MyStack → Default → Primary → Stack Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: my_stack.default.primary.stack_items[].stack_title_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  stack_title_text: prismic.RichTextField;
}

/**
 * Primary content in *MyStack → Default → Primary*
 */
export interface MyStackSliceDefaultPrimary {
  /**
   * My Stack Text field in *MyStack → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: my_stack.default.primary.my_stack_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  my_stack_text: prismic.RichTextField;

  /**
   * Stack Items field in *MyStack → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: my_stack.default.primary.stack_items[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  stack_items: prismic.GroupField<
    Simplify<MyStackSliceDefaultPrimaryStackItemsItem>
  >;
}

/**
 * Default variation for MyStack Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MyStackSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MyStackSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MyStack*
 */
type MyStackSliceVariation = MyStackSliceDefault;

/**
 * MyStack Shared Slice
 *
 * - **API ID**: `my_stack`
 * - **Description**: MyStack
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MyStackSlice = prismic.SharedSlice<
  "my_stack",
  MyStackSliceVariation
>;

/**
 * Item in *NavigationItem → Default → Primary → Child_link*
 */
export interface NavigationItemSliceDefaultPrimaryChildLinkItem {
  /**
   * Child Link field in *NavigationItem → Default → Primary → Child_link*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_item.default.primary.child_link[].child_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  child_link: prismic.Repeatable<prismic.LinkField>;
}

/**
 * Primary content in *NavigationItem → Default → Primary*
 */
export interface NavigationItemSliceDefaultPrimary {
  /**
   * Link field in *NavigationItem → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_item.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Child_link field in *NavigationItem → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_item.default.primary.child_link[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  child_link: prismic.GroupField<
    Simplify<NavigationItemSliceDefaultPrimaryChildLinkItem>
  >;
}

/**
 * Default variation for NavigationItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavigationItemSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NavigationItem*
 */
type NavigationItemSliceVariation = NavigationItemSliceDefault;

/**
 * NavigationItem Shared Slice
 *
 * - **API ID**: `navigation_item`
 * - **Description**: NavigationItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavigationItemSlice = prismic.SharedSlice<
  "navigation_item",
  NavigationItemSliceVariation
>;

/**
 * Default variation for ParallaxImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ParallaxImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *ParallaxImage*
 */
type ParallaxImageSliceVariation = ParallaxImageSliceDefault;

/**
 * ParallaxImage Shared Slice
 *
 * - **API ID**: `parallax_image`
 * - **Description**: A parallax scrolling image component
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ParallaxImageSlice = prismic.SharedSlice<
  "parallax_image",
  ParallaxImageSliceVariation
>;

/**
 * Primary content in *PfpSlice → Default → Primary*
 */
export interface PfpSliceSliceDefaultPrimary {
  /**
   * Profile Image field in *PfpSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pfp_slice.default.primary.profile_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  profile_image: prismic.ImageField<never>;
}

/**
 * Default variation for PfpSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PfpSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PfpSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PfpSlice*
 */
type PfpSliceSliceVariation = PfpSliceSliceDefault;

/**
 * PfpSlice Shared Slice
 *
 * - **API ID**: `pfp_slice`
 * - **Description**: PfpSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PfpSliceSlice = prismic.SharedSlice<
  "pfp_slice",
  PfpSliceSliceVariation
>;

/**
 * Item in *RecentPostSlider → Default → Primary → Related Post*
 */
export interface RecentPostSliderSliceDefaultPrimaryRelatedPostItem {
  /**
   * Blog Posts field in *RecentPostSlider → Default → Primary → Related Post*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: recent_post_slider.default.primary.related_post[].blog_posts
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  blog_posts: prismic.ContentRelationshipField<"blog_post">;
}

/**
 * Primary content in *RecentPostSlider → Default → Primary*
 */
export interface RecentPostSliderSliceDefaultPrimary {
  /**
   * Related Post field in *RecentPostSlider → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: recent_post_slider.default.primary.related_post[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  related_post: prismic.GroupField<
    Simplify<RecentPostSliderSliceDefaultPrimaryRelatedPostItem>
  >;
}

/**
 * Default variation for RecentPostSlider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RecentPostSliderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RecentPostSliderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RecentPostSlider*
 */
type RecentPostSliderSliceVariation = RecentPostSliderSliceDefault;

/**
 * RecentPostSlider Shared Slice
 *
 * - **API ID**: `recent_post_slider`
 * - **Description**: RecentPostSlider
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RecentPostSliderSlice = prismic.SharedSlice<
  "recent_post_slider",
  RecentPostSliderSliceVariation
>;

/**
 * Primary content in *RichTextBlock → Default → Primary*
 */
export interface RichTextBlockSliceDefaultPrimary {
  /**
   * Content field in *RichTextBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text_block.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichTextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichTextBlock*
 */
type RichTextBlockSliceVariation = RichTextBlockSliceDefault;

/**
 * RichTextBlock Shared Slice
 *
 * - **API ID**: `rich_text_block`
 * - **Description**: RichTextBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextBlockSlice = prismic.SharedSlice<
  "rich_text_block",
  RichTextBlockSliceVariation
>;

/**
 * Primary content in *Service → Default → Primary*
 */
export interface ServiceSliceDefaultPrimary {
  /**
   * Icon field in *Service → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service.default.primary.icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *Service → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Summary field in *Service → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.default.primary.summary
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  summary: prismic.RichTextField;

  /**
   * Service_detail field in *Service → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: service.default.primary.service_detail
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  service_detail: prismic.ContentRelationshipField<"service">;
}

/**
 * Default variation for Service Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServiceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Service*
 */
type ServiceSliceVariation = ServiceSliceDefault;

/**
 * Service Shared Slice
 *
 * - **API ID**: `service`
 * - **Description**: Service
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceSlice = prismic.SharedSlice<
  "service",
  ServiceSliceVariation
>;

/**
 * Item in *SocialSlice → Default → Primary → Social Network*
 */
export interface SocialSliceSliceDefaultPrimarySocialNetworkItem {
  /**
   * icon field in *SocialSlice → Default → Primary → Social Network*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: social_slice.default.primary.social_network[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;

  /**
   * Network URL field in *SocialSlice → Default → Primary → Social Network*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: social_slice.default.primary.social_network[].network_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  network_url: prismic.LinkField;
}

/**
 * Primary content in *SocialSlice → Default → Primary*
 */
export interface SocialSliceSliceDefaultPrimary {
  /**
   * Social Text field in *SocialSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: social_slice.default.primary.social_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  social_text: prismic.RichTextField;

  /**
   * Social Network field in *SocialSlice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: social_slice.default.primary.social_network[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_network: prismic.GroupField<
    Simplify<SocialSliceSliceDefaultPrimarySocialNetworkItem>
  >;
}

/**
 * Default variation for SocialSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SocialSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SocialSlice*
 */
type SocialSliceSliceVariation = SocialSliceSliceDefault;

/**
 * SocialSlice Shared Slice
 *
 * - **API ID**: `social_slice`
 * - **Description**: SocialSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialSliceSlice = prismic.SharedSlice<
  "social_slice",
  SocialSliceSliceVariation
>;

/**
 * Primary content in *WelcomeTextSlice → Default → Primary*
 */
export interface WelcomeTextSliceSliceDefaultPrimary {
  /**
   * Welcome Text Heading field in *WelcomeTextSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: welcome_text_slice.default.primary.welcome_text_heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  welcome_text_heading: prismic.RichTextField;

  /**
   * Welcome Text Subheading field in *WelcomeTextSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: welcome_text_slice.default.primary.welcome_text_subheading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  welcome_text_subheading: prismic.RichTextField;
}

/**
 * Default variation for WelcomeTextSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WelcomeTextSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WelcomeTextSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WelcomeTextSlice*
 */
type WelcomeTextSliceSliceVariation = WelcomeTextSliceSliceDefault;

/**
 * WelcomeTextSlice Shared Slice
 *
 * - **API ID**: `welcome_text_slice`
 * - **Description**: WelcomeTextSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WelcomeTextSliceSlice = prismic.SharedSlice<
  "welcome_text_slice",
  WelcomeTextSliceSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogDocument,
      BlogDocumentData,
      BlogDocumentDataSlicesSlice,
      BlogPostDocument,
      BlogPostDocumentData,
      BlogPostDocumentDataSlicesSlice,
      ExperienceDocument,
      ExperienceDocumentData,
      ExperienceDocumentDataSlicesSlice,
      ExperienceDetailDocument,
      ExperienceDetailDocumentData,
      ExperienceDetailDocumentDataSkillTagsItem,
      ExperienceDetailDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSlicesSlice,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ServiceDocument,
      ServiceDocumentData,
      ServiceDocumentDataSlicesSlice,
      ServicesDocument,
      ServicesDocumentData,
      ServicesDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataSocialLinksItem,
      SettingsDocumentDataFooterLinksItem,
      AllDocumentTypes,
      AboutMeSliceSlice,
      AboutMeSliceSliceDefaultPrimary,
      AboutMeSliceSliceVariation,
      AboutMeSliceSliceDefault,
      AvailablitySliceSlice,
      AvailablitySliceSliceDefaultPrimary,
      AvailablitySliceSliceVariation,
      AvailablitySliceSliceDefault,
      CompaniesIHaveWorkedWithSliceSlice,
      CompaniesIHaveWorkedWithSliceSliceDefaultPrimaryLogoItem,
      CompaniesIHaveWorkedWithSliceSliceDefaultPrimary,
      CompaniesIHaveWorkedWithSliceSliceVariation,
      CompaniesIHaveWorkedWithSliceSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      LogoSlice,
      LogoSliceDefaultPrimary,
      LogoSliceVariation,
      LogoSliceDefault,
      MyStackSlice,
      MyStackSliceDefaultPrimaryStackItemsItem,
      MyStackSliceDefaultPrimary,
      MyStackSliceVariation,
      MyStackSliceDefault,
      NavigationItemSlice,
      NavigationItemSliceDefaultPrimaryChildLinkItem,
      NavigationItemSliceDefaultPrimary,
      NavigationItemSliceVariation,
      NavigationItemSliceDefault,
      ParallaxImageSlice,
      ParallaxImageSliceVariation,
      ParallaxImageSliceDefault,
      PfpSliceSlice,
      PfpSliceSliceDefaultPrimary,
      PfpSliceSliceVariation,
      PfpSliceSliceDefault,
      RecentPostSliderSlice,
      RecentPostSliderSliceDefaultPrimaryRelatedPostItem,
      RecentPostSliderSliceDefaultPrimary,
      RecentPostSliderSliceVariation,
      RecentPostSliderSliceDefault,
      RichTextBlockSlice,
      RichTextBlockSliceDefaultPrimary,
      RichTextBlockSliceVariation,
      RichTextBlockSliceDefault,
      ServiceSlice,
      ServiceSliceDefaultPrimary,
      ServiceSliceVariation,
      ServiceSliceDefault,
      SocialSliceSlice,
      SocialSliceSliceDefaultPrimarySocialNetworkItem,
      SocialSliceSliceDefaultPrimary,
      SocialSliceSliceVariation,
      SocialSliceSliceDefault,
      WelcomeTextSliceSlice,
      WelcomeTextSliceSliceDefaultPrimary,
      WelcomeTextSliceSliceVariation,
      WelcomeTextSliceSliceDefault,
    };
  }
}
