import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";

import "./globals.css";
import { geistMono, geistSans } from "@/app/fonts";
import { cn } from "@/app/lib/utils";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(geistSans.variable, geistMono.variable, "antialiased")}
      >
        <ThemeProvider attribute="data-theme">
          <Header />
          <main className="from-primary/20 via-accent/20 to-secondary/20 dark:from-primary/80 dark:via-accent/80 dark:to-secondary/80 bg-gradient-radial from-center min-h-screen flex flex-col bg-[length:100%_100%]">
            {children}
          </main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
