// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  logo: dynamic(() => import("./Logo")),
  navigation_item: dynamic(() => import("./NavigationItem")),
  parallaxed_banner_with_title: dynamic(
    () => import("./ParallaxedBannerWithTitle"),
  ),
  rich_text_block: dynamic(() => import("./RichTextBlock")),
};
